# Basic Operations
# How do you create a NumPy array of integers from 1 to 10?
# How can you generate an array of 10 random numbers between 0 and 1?
# How do you create a 3x3 identity matrix using NumPy?
# How can you generate 50 values evenly spaced between 0 and 5?
# How do you create a 5x5 matrix with values ranging from 1 to 25?


In [2]:
import numpy as np
arr1 = np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
import numpy as np
arr2 = np.random.rand(10,1)
print(arr2)

[[0.47689567]
 [0.14964351]
 [0.66243592]
 [0.4350804 ]
 [0.71814514]
 [0.74383042]
 [0.59634091]
 [0.20858811]
 [0.86722656]
 [0.14827202]]


In [4]:
arr3 = np.ones(shape=(3,3))
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
arr4 = np.linspace(0,5,50)
print(arr4)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [6]:
arr5 = np.arange(0,5,0.1)
print(arr5)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


In [7]:
arr6 = np.arange(1,26)
print(arr6)
arr6 = arr6.reshape(5,5)
print(arr6)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# Array Manipulation
# How do you reshape a 1D array into a 3x4 matrix?
# How can you flatten a 2D array into a 1D array?
# How do you concatenate two 1D arrays [1, 2, 3] and [4, 5, 6]?
# How do you stack two 2D arrays vertically and horizontally?
# How can you split an array into 3 equal parts?

In [9]:
arr7 = np.arange(1,13)
arr7 = arr7.reshape(3,4)
print(arr7)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
arr8 = np.array([[1,2,3],[4,5,6]])
arr9 = arr8.ravel()
print(arr9)

[1 2 3 4 5 6]


In [11]:
arr10 = np.array([1,2,3])
arr11 = np.array([4,5,6])
arr12 = np.concatenate((arr10,arr11))
print(arr12)

[1 2 3 4 5 6]


In [12]:
arr13 =np.array([1,2,3])
arr14 =np.array([4,5,6])
arr15 =np.vstack((arr13,arr14))
print(arr15)

[[1 2 3]
 [4 5 6]]


In [13]:
arr13 =np.array([1,2,3])
arr14 =np.array([4,5,6])
arr15 =np.hstack((arr13,arr14))
print(arr15)

[1 2 3 4 5 6]


In [14]:
arr16 = np.array([1,2,3,4,5,6,7,8,9])
arr16 = np.split(arr16,3)
print(arr16)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# Indexing & Slicing
# How do you extract the second column of a 3x3 matrix?
# How can you get all elements greater than 15 in a NumPy array?
# How do you replace all even numbers in an array with -1?
# How can you reverse a NumPy array without using a loop?
# How do you extract the diagonal elements of a square matrix?

In [16]:
import numpy as np
arr17= np.arange(1,10).reshape(3,3)
print(arr17)
arr18=np.array((arr17[0][1],arr17[1][1],arr17[2][1]))
print(arr18)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]


In [17]:
arr19=np.array([12,15,17,18,19,20,26,27])
print(arr19)
result=np.extract(arr19>15,arr19)
print(result)
result=arr19[arr19>15]
print(result)

[12 15 17 18 19 20 26 27]
[17 18 19 20 26 27]
[17 18 19 20 26 27]


In [18]:
arr20 = np.array([1,2,3,4,5,6,7,8,9])
result = []
for i in arr20:
    if i%2!=0:
        result.append(i)
    else:
        result.append(-1)

print(np.array(result))

# second method
arr20[arr20%2==0]=-1
print(arr20)        

[ 1 -1  3 -1  5 -1  7 -1  9]
[ 1 -1  3 -1  5 -1  7 -1  9]


In [19]:
arr20 = np.array([1,2,3,4,5,6,7,8,9])
print(arr20[::-1])

[9 8 7 6 5 4 3 2 1]


In [20]:
arr17= np.arange(1,10).reshape(3,3)
print(arr17)
print(np.array((arr17[0][0],arr17[1][1],arr17[2][2])))

# second method
result = np.diag(arr17)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[1 5 9]


# Mathematical & Statistical Operations
# Find the sum, mean, standard deviation, and variance of an array.
# Compute the dot product of two matrices:
# Normalize an array so that values range between 0 and 1.
# Find the row-wise maximum and column-wise minimum of a 2D array.
# Generate an array of 10 random numbers and sort them in ascending order.


In [22]:
arr20 = np.array([1,2,3,4,5,6,7,8,9])
mean = np.mean(arr20)
print(mean)
sum1 = np.sum(arr20)
print(sum1)
std = np.std(arr20)
print(std)
var = np.var(arr20)
print(var)

5.0
45
2.581988897471611
6.666666666666667


In [23]:
arr0 = np.arange(1,10).reshape(3,3)
arr1 = np.arange(11,20).reshape(3,3)
print(arr0)
print(arr1)
result = arr0.dot(arr1)
print(result)

# second method
dot_product = arr0 @ arr1
print(dot_product)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [24]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
normal = (a-a.min())/(a.max() - a.min())
print(normal)

[1 2 3 4 5 6 7 8 9]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [25]:
b = np.arange(1,9).reshape(2,4)
print(b)
print(np.max(b,axis=1))
print(np.min(b,axis=0))

[[1 2 3 4]
 [5 6 7 8]]
[4 8]
[1 2 3 4]


In [26]:
r = np.random.randint(1,100,size=(10))
print(r)
print(np.sort(r))
print(r.ndim)

[25 49 23 53 20  8 55 34 10 20]
[ 8 10 20 20 23 25 34 49 53 55]
1


# Boolean Indexing & Filtering
# How do you extract all numbers divisible by 3 from an array?
# How can you replace all numbers greater than 50 with 0 in an array?
# How do you count the number of non-zero elements in an array?
# How do you find and return the indices where elements in an array are negative?
# How can you clip values in a matrix so that all elements greater than 10 are set to 10?

In [28]:
a = np.random.randint(1,100,size=(10))
print(a)
result = a[a%3==0]
print(result)


[96 88 66 21 27 18 58 71 94 49]
[96 66 21 27 18]


In [29]:
a = np.random.randint(1,100,size=(10))
print(a)
a[a>50]=0
print(a)

[80 94 38 80 84 73 50  1 50  5]
[ 0  0 38  0  0  0 50  1 50  5]


In [30]:
a = np.random.randint(0,9,size=(10))
print(a)
print(np.count_nonzero(a))

[8 4 3 1 5 4 1 6 3 2]
10


In [31]:
a = np.array([1,2,3,4,-1,-2,-3,-4])
a= np.where(a<0)
print(a)

(array([4, 5, 6, 7], dtype=int64),)


In [32]:
a = np.arange(5,14).reshape(3,3)
print(a)
a[a>10]=10
print(a)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[ 5  6  7]
 [ 8  9 10]
 [10 10 10]]


# Advanced Topics
# How do you find the inverse of a matrix using NumPy?
# How can you compute the eigenvalues and eigenvectors of a matrix?
# How do you solve a system of linear equations using NumPy?
# How can you generate a random 4x4 matrix and replace all values below the mean with 0?
# How do you compute the pairwise Euclidean distance between rows of a matrix?


In [34]:
import numpy as np
a= np.arange(1,10).reshape(3,3)
print(a)
print(np.linalg.det(a))
result = np.linalg.inv(a)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [35]:
a= np.arange(1,10).reshape(3,3)
print(a)
eigen_values,eigen_vectors = np.linalg.eig(a)
print(eigen_values)
print(eigen_vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [36]:
a = np.array([[1,2]
              ,[3,4]])
b = np.array([7,8])
result = np.linalg.solve(a,b)
print(result)

[-6.   6.5]


In [37]:
a = np.arange(1,17).reshape(4,4)
print(a)
mean = np.mean(a)
print(mean)
a[a<mean] = 0
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
8.5
[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 9 10 11 12]
 [13 14 15 16]]


In [38]:
import numpy as np
c = np.array([[1, 2],[3, 4],[5, 6]])
dists = np.linalg.norm(c[:, np.newaxis] - c, axis=2)
print(dists)


[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [39]:
a = np.array([[500,1500],[700,1200],[400,900],[900,1800],[650,1600]])
print(a)

[[ 500 1500]
 [ 700 1200]
 [ 400  900]
 [ 900 1800]
 [ 650 1600]]


In [40]:
diff = a[:,np.newaxis,:] - a[np.newaxis,:,:]
distance = np.sqrt(np.sum(diff**2,axis=-1))
print(distance.round(2))

[[   0.    360.56  608.28  500.    180.28]
 [ 360.56    0.    424.26  632.46  403.11]
 [ 608.28  424.26    0.   1029.56  743.3 ]
 [ 500.    632.46 1029.56    0.    320.16]
 [ 180.28  403.11  743.3   320.16    0.  ]]


In [41]:
import numpy as np
transactions = np.array([
    [50, 14],
    [200, 16],
    [500000, 2],
    [30, 10], 
    [700, 3],
    [100, 18]
])
mean_amount = np.mean(transactions[:, 0])
std_amount = np.std(transactions[:, 0]) 
suspicious = transactions[:, 0] > (mean_amount + 2 * std_amount)

print("Suspicious Transactions:")
print(transactions[suspicious])


Suspicious Transactions:
[[500000      2]]


# 1️⃣Create a 5x5 matrix with values from 1 to 25
Write a NumPy program to create a 5x5 matrix filled with values from 1 to 25.

In [43]:
import numpy as np
arr = np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# 2️⃣ Replace all even numbers in a NumPy array with -1

In [45]:
arr[arr%2==0]=-1
print(arr)

[[ 1 -1  3 -1  5]
 [-1  7 -1  9 -1]
 [11 -1 13 -1 15]
 [-1 17 -1 19 -1]
 [21 -1 23 -1 25]]


#  Find the mean and standard deviation of a NumPy array
Create a 1D NumPy array of size 10 with random values between 10 and 100. Compute and print its mean and standard deviation.


In [47]:
arr1 = np.random.randint(10,100,10)
print(arr1)
print(arr1.mean())
print(arr1.std())

[39 59 24 22 42 20 62 41 33 41]
38.3
13.609188072769072


# 4️⃣ Stack two NumPy arrays vertically and horizontally

In [49]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.vstack((a,b))
print(result)
result2 = np.hstack((a,b))
print(result2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# 5️⃣ Find the index of the maximum value in a NumPy array

In [51]:
arr = np.array([4, 18, 25, 9, 30, 12])
result = np.argmax(arr)
print(result)

4


# 1️⃣ Create a NumPy array of shape (3,3) filled with random floating-point numbers
Generate a 3×3 matrix where each element is a random float between 0 and 1.

In [53]:
arr0 = np.random.rand(3,3)
print(arr0)

[[0.05327919 0.17074748 0.9991093 ]
 [0.28347006 0.01849354 0.30401347]
 [0.8733191  0.36181611 0.80667515]]


#  Find the sum of all elements in a NumPy array

In [55]:
arr4 = np.random.randint(1,20,16).reshape(4,4)
print(arr4)
print(arr4.sum(()))

[[ 9  3 17 19]
 [ 3 15 18  9]
 [ 4  2 16  7]
 [ 6 14  9 12]]
[[ 9  3 17 19]
 [ 3 15 18  9]
 [ 4  2 16  7]
 [ 6 14  9 12]]


# 4️⃣ Normalize a NumPy array (scale values between 0 and 1)



In [57]:
arr = np.array([5, 15, 25, 35, 45])
result = []
maxi = arr.max()
mini = arr.min()
for x in arr:
    normal = (x-mini)/(maxi-mini)
    result.append(normal)
print(result)

[0.0, 0.25, 0.5, 0.75, 1.0]


In [58]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
unique_values, counts = np.unique(arr, return_counts=True)
print(unique_values)
print(counts)

[1 2 3 4]
[1 2 3 4]


# 1. Stock Market Data Analysis (Moving Average Calculation)
# Problem: Compute a 7-day moving average of stock prices.

In [60]:
import numpy as np
stock_prices = np.array([100, 102, 101, 105, 107, 110, 108, 112, 115, 118])
window_size = 7

moving_avg = np.convolve(stock_prices, np.ones(window_size) / window_size, mode='valid')
print(moving_avg.round(2))


[104.71 106.43 108.29 110.71]


# 2. Weather Data Analysis (Temperature Anomalies Detection)
# Problem: Given daily temperature readings for a month, detect anomalies (days with temperatures significantly different from the mean).

In [62]:
import numpy as np
temperatures = np.array([30, 32, 45, 35, 28, 33, 31, 40, 27, 26, 34, 66, 37, 25, 39, 38, 24, 30, 31, 29, 32, 33, 35, 30, 28, 37, 26, 40, 74, 29])

mean_temp = np.mean(temperatures)
std_temp = np.std(temperatures)
threshold = 2 * std_temp

anomalies = temperatures[np.abs(temperatures - mean_temp) > threshold]
print("Temperature anomalies:", anomalies)


Temperature anomalies: [66 74]


# 1️⃣ Matrix Rotation (90 Degrees Clockwise) 🔄
# 📌 Problem: Given a NxN matrix, rotate it 90 degrees clockwise using only NumPy operations.

In [64]:
import numpy as np
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

rotated_matrix = np.transpose(matrix)[::-1]

print("Original Matrix:\n", matrix)
print("Rotated Matrix:\n", rotated_matrix)


Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rotated Matrix:
 [[3 6 9]
 [2 5 8]
 [1 4 7]]


# 2️⃣ Distance Between Two Points 📍
# 📌 Problem: Given two points in a 3D space, calculate the Euclidean distance between them.

In [66]:
import numpy as np

point_A = np.array([3, 4, 5])
point_B = np.array([7, 1, 9])

distance = np.linalg.norm(point_A - point_B)
print(f"EUCLIDEN DISTANC IS {distance}")


EUCLIDEN DISTANC IS 6.4031242374328485


# 1️⃣ Flight Delay Analysis (Airline Industry) ✈️
# 📌 Problem: An airline wants to analyze flight delays. Given an array of flight delay times (in minutes), calculate:
# 💠The average delay
# 💠The percentage of flights delayed more than 30 minutes

In [68]:
import numpy as np
flight_record = np.array([15, -5, 25, 45, 40, 60, -20, 15, 50, 0, 10, 30, 25])

average_delay = np.mean(flight_record)
delay_flights = np.sum(flight_record > 30) / len(flight_record) * 100

print(f"Average Delay: {average_delay.round(2)} minutes")
print(f"Percentage of Flights Delayed More Than 30 Minutes: {delay_flights} %")

Average Delay: 22.31 minutes
Percentage of Flights Delayed More Than 30 Minutes: 30.76923076923077 %


# 2️⃣ Earthquake Magnitude Analysis (Seismology) 🌍
# 📌 Problem: Seismologists want to analyze earthquake data. Given an array of earthquake magnitudes, determine:
# 💠The strongest earthquake recorded
# 💠The number of earthquakes above 5.0 magnitude (considered significant)

In [70]:
import numpy as np
earthquake_mag = np.array([2.5, 3.2, 4.8, 5.1, 6.3, 2.9, 5.0, 7.1, 4.2, 2.4, 5.7])

strongest_earthquake = np.max(earthquake_mag)
sig_quakes = np.sum(earthquake_mag > 5.0)

print(f"Strongest Earthquake Magnitude: {strongest_earthquake}")
print(f"Number of Significant Earthquakes: {sig_quakes}")

Strongest Earthquake Magnitude: 7.1
Number of Significant Earthquakes: 4


# 1️⃣ Movie Ratings Analysis (Entertainment Industry) 🎬
# 📌 Problem: A streaming platform wants to analyze user ratings of movies. Given a NumPy array of movie ratings (scale: 1 to 5), calculate:
# ✅ The average rating
# ✅ The percentage of 5-star ratings
# ✅ The most common rating

In [72]:
import numpy as np

ratings = np.random.randint(1,6,20)
print(ratings)
avg_rating = np.mean(ratings)
five_star_percentage = np.sum(ratings == 5) / len(ratings) * 100
common_rating = np.bincount(ratings).argmax()

print(f"Average Movie Rating: {avg_rating} ⭐")
print(f"Percentage of 5 ⭐ Ratings: {five_star_percentage} %")
print(f"Most Common Rating: {common_rating} ⭐")


[5 1 3 2 4 5 3 2 4 3 5 2 3 3 2 2 1 1 5 4]
Average Movie Rating: 3.0 ⭐
Percentage of 5 ⭐ Ratings: 20.0 %
Most Common Rating: 2 ⭐


# 2️⃣ Financial Portfolio Risk Analysis (Investment) 💰
# 📌 Problem: A financial analyst wants to measure the volatility (risk) of a stock portfolio. Given daily percentage returns of stocks, calculate:
# ✅ The average daily return
# ✅ The portfolio risk (standard deviation of returns)

In [74]:
import numpy as np
values = np.array([-1,-1.5,2,4,-0.5,2.5,1.5,-1.15,1,3,3.5])

avg_return = np.mean(values)
risk = np.std(values)

print(f"Average Daily Return: {avg_return} %")
print(f"Portfolio Risk (Volatility): {risk} %")


Average Daily Return: 1.2136363636363636 %
Portfolio Risk (Volatility): 1.891859463967913 %


# 1️⃣ DNA Sequence Analysis (Bioinformatics) 🧬
# 📌 Problem: Scientists analyze DNA sequences to study genetic patterns. Given a DNA sequence represented as a NumPy character array, count the occurrences of each nucleotide:

# ✅ Find the frequency of A (Adenine), T (Thymine), C (Cytosine), and G (Guanine).

In [76]:
import numpy as np
dna_data = np.array(list("ATGCGTACGTACGTAATTGCCAAGGGTCCATGA"))

nuc, counts = np.unique(dna_data, return_counts=True)
nuc_counts = dict(zip(nuc, counts))

print(f"Nucleotide Frequencies: {nuc_counts}")

Nucleotide Frequencies: {'A': 9, 'C': 7, 'G': 9, 'T': 8}


# 2️⃣ Warehouse Inventory Optimization (Supply Chain) 📦
# 📌 Problem: A warehouse manager wants to optimize storage by rearranging items based on their weights. Given an array of item weights (kg), sort them in descending order and get the top 3 heaviest items.

# ✅ Sort the weights in descending order and extract the top 3 items.

In [78]:
import numpy as np

weights = np.array([15.6,7.8,2.2,19.2,0.5,22.8,25.7,3.6,9.99,6.8])
sort_weights = np.sort(weights)[::-1]
top_3_heavy = sort_weights[:3]

print(f"Sorted Weights in descending: {sort_weights}")
print(f"Top 3 Heaviest Items: {top_3_heavy}")

Sorted Weights in descending: [25.7  22.8  19.2  15.6   9.99  7.8   6.8   3.6   2.2   0.5 ]
Top 3 Heaviest Items: [25.7 22.8 19.2]


# 1️⃣ Customer Spending Pattern Analysis (Retail) 🛒
# 📌 Problem: A retail store tracks customer spending. Given an array of customer purchase amounts, identify customers who spent above the 90th percentile, marking them as VIP customers.

# ✅ Find the spending threshold for VIP customers and extract their indices.

In [80]:
import numpy as np

spending = np.array([120,300,600,700,300,270,490,200,234,987,654,100])
vip_threshold = np.percentile(spending, 90)
vip = np.where(spending > vip_threshold)[0]

print(f"VIP Customer Indices: {vip}")
print(f"VIP Spending Values: {spending[vip]}")


VIP Customer Indices: [3 9]
VIP Spending Values: [700 987]


# 2️⃣ Smart Energy Consumption Analysis (IoT) ⚡
# 📌 Problem: A smart meter records hourly electricity consumption for a household. Given a NumPy array of hourly readings, calculate the cumulative energy consumption over time to monitor usage trends.

# ✅ Compute cumulative energy consumption.

In [82]:
import numpy as np

energy_usage = np.array([2.3,5.6,1.3,9.9,1.0,1.9,5.8])
cumulative_usage = np.cumsum(energy_usage)

print(f"Hourly Energy Usage: {energy_usage}")
print(f"Cumulative Energy Consumption: {cumulative_usage}")

Hourly Energy Usage: [2.3 5.6 1.3 9.9 1.  1.9 5.8]
Cumulative Energy Consumption: [ 2.3  7.9  9.2 19.1 20.1 22.  27.8]


# 1️⃣ Online Learning Platform – Quiz Performance Analysis 🎓
# 📌 Problem: An e-learning platform tracks student quiz scores. Given an array of student scores, classify them into performance levels:

# Low (<50%)

# Average (50-75%)

# High (>75%)

# ✅ Categorize student scores using NumPy’s vectorized operations.

In [84]:
import numpy as np
scores = np.array([50,45,76,87,43,23,56,75,67,43,24,23,98,10,44,55,66,77,88])

conditions = [scores < 50,(scores >= 50) & (scores <= 75),scores > 75]
categories = ["Low", "Average", "High"]
performance_levels = np.select(conditions, categories)

print(f"Student Performance Levels: {performance_levels}")

Student Performance Levels: ['Average' 'Low' 'High' 'High' 'Low' 'Low' 'Average' 'Average' 'Average'
 'Low' 'Low' 'Low' 'High' 'Low' 'Low' 'Average' 'Average' 'High' 'High']


# 2️⃣ Inventory Restocking Optimization (Retail) 🏪
# 📌 Problem: A supermarket tracks daily stock levels of a popular product. Given an array of daily stock counts, identify days when stock fell below the restocking threshold (20 units) to trigger automatic replenishment.

# ✅ Find days that require restocking.

In [86]:
import numpy as np
stock_level = np.array([90,60,30,50,10,15,70,33,22,10,20])

threshold = 20
restock_days = np.where(stock_level <= threshold)[0]

print(f"Days to Restock: {restock_days}")
print(f"Stock Levels on These Days: {stock_level[restock_days]}")

Days to Restock: [ 4  5  9 10]
Stock Levels on These Days: [10 15 10 20]


# 1️⃣ Customer Churn Risk Prediction (Telecom) 📞
# 📌 Problem: A telecom company tracks monthly call durations (in minutes) for its customers. Customers with a drop of more than 30% in call duration compared to the previous month might be at risk of churning (leaving the service).

# ✅ Identify customers with a 30%+ drop in call usage compared to the previous month.

In [88]:
import numpy as np

call_time = np.array([250, 240, 230, 200, 140, 100, 220, 180, 160, 80])
percent_change = np.diff(call_time) / call_time[:-1] * 100
churn_risk_months = np.where(percent_change < -30)[0] + 1

print(f"Months with High Churn Risk: {churn_risk_months}")
print(f"Percentage Drop in These Months: {percent_change[churn_risk_months - 1]}")

Months with High Churn Risk: [9]
Percentage Drop in These Months: [-50.]


# 2️⃣ E-Commerce Product Rating Normalization 🛒
# 📌 Problem: An e-commerce website collects product ratings from different sources, but they use different scales (e.g., some are out of 5 stars, others out of 10). Given an array of ratings with mixed scales, normalize all ratings to a 0-1 scale for comparison.

# ✅ Convert all ratings to a 0-1 scale.

In [90]:
import numpy as np

ratings = np.array([4.5, 3.8, 8, 7.2, 4.9, 9.5, 2, 5, 10, 6])
normalized_ratings = np.where(ratings > 5, ratings / 10, ratings / 5)

print(f"Normalized Ratings (0-1 scale): {normalized_ratings}")

Normalized Ratings (0-1 scale): [0.9  0.76 0.8  0.72 0.98 0.95 0.4  1.   1.   0.6 ]


# 1️⃣ Hospital Patient Monitoring – Detecting Critical Heart Rates ❤️
# 📌 Problem: A hospital tracks the heart rates (BPM) of patients in the ICU. A patient is in critical condition if their heart rate is below 50 BPM or above 120 BPM.

# ✅ Identify patients with critical heart rates.

In [92]:
import numpy as np

heart_rates = np.array([89,67,98,110,20,59,69,96,79,97,122,150])
critical = np.where((heart_rates < 50) | (heart_rates > 120))[0]

print(f"Patients in Critical Condition (Index): {critical}")
print(f"Heart Rates of These Patients: {heart_rates[critical]}")


Patients in Critical Condition (Index): [ 4 10 11]
Heart Rates of These Patients: [ 20 122 150]


# Movie Recommendation System – Finding Similar Users 🎬
# 📌 Problem: A streaming platform wants to recommend movies based on user rating similarity. Given a matrix where rows represent users and columns represent movies, find users with the most similar preferences using cosine similarity.

# ✅ Find the user who is most similar to a given user based on movie ratings.

In [94]:
import numpy as np

ratings = np.array([
    [5,4,3,2,1],
    [4,5,2,1,3], 
    [1,2,3,4,5], 
    [5,5,2,2,1]  
])
user_idx = 0
similarities = np.dot(ratings, ratings[user_idx]) / (np.linalg.norm(ratings, axis=1) * np.linalg.norm(ratings[user_idx]))
most_similar_user = np.argsort(-similarities)[1]

print(f"Most similar user to User 0: {most_similar_user}")
print(f"Similarity Scores: {similarities}")


Most similar user to User 0: 3
Similarity Scores: [1.         0.92727273 0.63636364 0.98306147]
